import type { Destination, Expense, GroupMember, Journey, TravelGroup } from "./types";

export const CITIES = [
  { code: "BOM", name: "Mumbai" },
  { code: "DEL", name: "Delhi" },
  { code: "BLR", name: "Bengaluru" },
  { code: "GOI", name: "Goa" },
  { code: "JAI", name: "Jaipur" },
  { code: "HYD", name: "Hyderabad" },
  { code: "PNQ", name: "Pune" },
  { code: "AMD", name: "Ahmedabad" },
  { code: "CCU", name: "Kolkata" },
  { code: "MAA", name: "Chennai" },
  { code: "IXC", name: "Chandigarh" },
  { code: "LKO", name: "Lucknow" },
];

export const MONTHS = [
  "Jan",
  "Feb",
  "Mar",
  "Apr",
  "May",
  "Jun",
  "Jul",
  "Aug",
  "Sep",
  "Oct",
  "Nov",
  "Dec",
];

const base = {
  from: "Mumbai",
  fromCode: "BOM",
  to: "Delhi",
  toCode: "DEL",
  arrivalDayOffset: 0,
};

export const JOURNEYS: Journey[] = [
  {
    ...base,
    id: "fl-6e2043",
    mode: "flight",
    operator: "IndiGo",
    serviceName: "IndiGo Direct",
    code: "6E 2043",
    departure: "06:20",
    arrival: "08:35",
    durationMin: 135,
    price: 5240,
    studentPrice: 4690,
    seatClass: "Economy",
    stops: 0,
    onTimePct: 88,
    co2Kg: 121,
    refundable: false,
    amenities: ["Cabin bag 7kg", "Web check-in", "Paid meals"],
    accessibility: {
      stepFreeBoarding: true,
      wheelchairAssistance: true,
      accessibleToilet: true,
      attendantSeat: true,
    },
    safety: {
      operatorReliability: 88,
      daytimeArrival: true,
      transferRating: 82,
      womenOnlyOption: false,
      cctv: true,
    },
  },
  {
    ...base,
    id: "fl-ai866",
    mode: "flight",
    operator: "Air India",
    serviceName: "Air India Direct",
    code: "AI 866",
    departure: "09:45",
    arrival: "11:55",
    durationMin: 130,
    price: 6180,
    seatClass: "Economy",
    stops: 0,
    onTimePct: 79,
    co2Kg: 128,
    refundable: true,
    amenities: ["Meal included", "25kg baggage", "Seat selection"],
    accessibility: {
      stepFreeBoarding: true,
      wheelchairAssistance: true,
      accessibleToilet: true,
      attendantSeat: true,
    },
    safety: {
      operatorReliability: 81,
      daytimeArrival: true,
      transferRating: 79,
      womenOnlyOption: false,
      cctv: true,
    },
  },
  {
    ...base,
    id: "fl-sg8194",
    mode: "flight",
    operator: "SpiceJet",
    serviceName: "SpiceJet Saver",
    code: "SG 8194",
    departure: "22:10",
    arrival: "00:30",
    arrivalDayOffset: 1,
    durationMin: 140,
    price: 4390,
    studentPrice: 3990,
    seatClass: "Economy",
    stops: 0,
    onTimePct: 68,
    co2Kg: 133,
    refundable: false,
    amenities: ["Cabin bag 7kg", "Paid meals"],
    accessibility: {
      stepFreeBoarding: false,
      wheelchairAssistance: true,
      accessibleToilet: true,
      attendantSeat: false,
    },
    safety: {
      operatorReliability: 66,
      daytimeArrival: false,
      transferRating: 61,
      womenOnlyOption: false,
      cctv: true,
    },
  },
  {
    ...base,
    id: "tr-22221",
    mode: "train",
    operator: "Indian Railways",
    serviceName: "Vande Bharat Express",
    code: "22221",
    departure: "05:55",
    arrival: "22:05",
    durationMin: 970,
    price: 3210,
    studentPrice: 2570,
    seatClass: "Chair Car (CC)",
    stops: 6,
    onTimePct: 92,
    co2Kg: 21,
    refundable: true,
    amenities: ["Meals onboard", "Charging points", "Wi-Fi infotainment"],
    accessibility: {
      stepFreeBoarding: true,
      wheelchairAssistance: true,
      accessibleToilet: true,
      attendantSeat: true,
    },
    safety: {
      operatorReliability: 92,
      daytimeArrival: false,
      transferRating: 88,
      womenOnlyOption: false,
      cctv: true,
    },
  },
  {
    ...base,
    id: "tr-12951",
    mode: "train",
    operator: "Indian Railways",
    serviceName: "Mumbai Rajdhani Express",
    code: "12951",
    departure: "17:00",
    arrival: "08:32",
    arrivalDayOffset: 1,
    durationMin: 932,
    price: 2755,
    studentPrice: 2205,
    seatClass: "3A",
    stops: 4,
    onTimePct: 90,
    co2Kg: 24,
    refundable: true,
    amenities: ["All meals included", "Bedroll", "Pantry car"],
    accessibility: {
      stepFreeBoarding: false,
      wheelchairAssistance: true,
      accessibleToilet: true,
      attendantSeat: true,
    },
    safety: {
      operatorReliability: 90,
      daytimeArrival: true,
      transferRating: 86,
      womenOnlyOption: true,
      cctv: true,
    },
  },
  {
    ...base,
    id: "tr-12953",
    mode: "train",
    operator: "Indian Railways",
    serviceName: "August Kranti Rajdhani",
    code: "12953",
    departure: "17:40",
    arrival: "09:55",
    arrivalDayOffset: 1,
    durationMin: 975,
    price: 1980,
    studentPrice: 1580,
    seatClass: "Sleeper (SL)",
    stops: 7,
    onTimePct: 84,
    co2Kg: 19,
    refundable: true,
    amenities: ["Pantry car", "Charging points"],
    accessibility: {
      stepFreeBoarding: false,
      wheelchairAssistance: false,
      accessibleToilet: false,
      attendantSeat: false,
    },
    safety: {
      operatorReliability: 84,
      daytimeArrival: true,
      transferRating: 74,
      womenOnlyOption: true,
      cctv: false,
    },
  },
  {
    ...base,
    id: "bs-vol-101",
    mode: "bus",
    operator: "VRL Travels",
    serviceName: "Volvo AC Sleeper",
    code: "VRL 4102",
    departure: "18:30",
    arrival: "16:45",
    arrivalDayOffset: 1,
    durationMin: 1335,
    price: 2150,
    studentPrice: 1830,
    seatClass: "AC Sleeper (2+1)",
    stops: 3,
    onTimePct: 74,
    co2Kg: 42,
    refundable: false,
    amenities: ["Blanket", "Charging point", "Live tracking"],
    accessibility: {
      stepFreeBoarding: false,
      wheelchairAssistance: false,
      accessibleToilet: false,
      attendantSeat: false,
    },
    safety: {
      operatorReliability: 74,
      daytimeArrival: true,
      transferRating: 70,
      womenOnlyOption: true,
      cctv: true,
    },
  },
  {
    ...base,
    id: "bs-int-220",
    mode: "bus",
    operator: "IntrCity SmartBus",
    serviceName: "SmartBus AC Seater",
    code: "IC 2207",
    departure: "20:15",
    arrival: "20:10",
    arrivalDayOffset: 1,
    durationMin: 1435,
    price: 1690,
    studentPrice: 1420,
    seatClass: "AC Seater",
    stops: 5,
    onTimePct: 71,
    co2Kg: 38,
    refundable: true,
    amenities: ["Onboard host", "Women-only rows", "Sanitised cabin"],
    accessibility: {
      stepFreeBoarding: true,
      wheelchairAssistance: true,
      accessibleToilet: false,
      attendantSeat: true,
    },
    safety: {
      operatorReliability: 78,
      daytimeArrival: false,
      transferRating: 80,
      womenOnlyOption: true,
      cctv: true,
    },
  },
];

export interface Combo {
  id: string;
  label: string;
  legs: string[];
  price: number;
  durationMin: number;
  co2Kg: number;
  saving: number;
  note: string;
}

export const COMBOS: Combo[] = [
  {
    id: "combo-1",
    label: "Train + Flight",
    legs: ["Mumbai → Surat · Vande Bharat", "Surat → Delhi · IndiGo"],
    price: 4120,
    durationMin: 465,
    co2Kg: 78,
    saving: 1120,
    note: "Beats a direct morning flight by ₹1,120 with only 45 min more travel.",
  },
  {
    id: "combo-2",
    label: "Bus + Train",
    legs: ["Mumbai → Vadodara · Volvo AC", "Vadodara → Delhi · Rajdhani"],
    price: 2280,
    durationMin: 1080,
    co2Kg: 31,
    saving: 930,
    note: "Cheapest low-carbon pairing on this route this week.",
  },
  {
    id: "combo-3",
    label: "Flight + Train",
    legs: ["Mumbai → Jaipur · SpiceJet", "Jaipur → Delhi · Vande Bharat"],
    price: 5010,
    durationMin: 420,
    co2Kg: 95,
    saving: 0,
    note: "Adds a Jaipur stopover without paying for a second ticket day.",
  },
];

export const DESTINATIONS: Destination[] = [
  {
    id: "goa",
    name: "Goa",
    state: "Goa",
    tagline: "Beach shacks, Latin quarters and monsoon-green hills",
    bestMonths: ["Jun", "Jul", "Aug"],
    avoidMonths: ["Dec", "Jan"],
    monthlyIndex: [72, 64, 58, 52, 44, 32, 28, 30, 40, 62, 84, 97],
    priceIndex: 84,
    verdict: "wait",
    cheapestMode: "train",
    fromMumbai: 1290,
    emoji: "🏖️",
  },
  {
    id: "manali",
    name: "Manali",
    state: "Himachal Pradesh",
    tagline: "Deodar forests, Solang snow and Old Manali cafés",
    bestMonths: ["Feb", "Mar", "Nov"],
    avoidMonths: ["May", "Jun"],
    monthlyIndex: [48, 40, 44, 60, 92, 96, 74, 66, 58, 70, 42, 56],
    priceIndex: 41,
    verdict: "now",
    cheapestMode: "bus",
    fromMumbai: 2480,
    emoji: "🏔️",
  },
  {
    id: "jaipur",
    name: "Jaipur",
    state: "Rajasthan",
    tagline: "Pink City forts, stepwells and bazaar breakfasts",
    bestMonths: ["Aug", "Sep"],
    avoidMonths: ["Dec", "Jan"],
    monthlyIndex: [80, 72, 60, 52, 40, 36, 34, 30, 33, 66, 88, 94],
    priceIndex: 55,
    verdict: "watch",
    cheapestMode: "train",
    fromMumbai: 1640,
    emoji: "🕌",
  },
  {
    id: "rishikesh",
    name: "Rishikesh",
    state: "Uttarakhand",
    tagline: "Ganga aarti, rafting season and riverside yoga",
    bestMonths: ["Feb", "Mar"],
    avoidMonths: ["Jul", "Aug"],
    monthlyIndex: [52, 38, 40, 58, 70, 78, 88, 84, 62, 60, 46, 50],
    priceIndex: 38,
    verdict: "now",
    cheapestMode: "train",
    fromMumbai: 1980,
    emoji: "🛶",
  },
  {
    id: "udaipur",
    name: "Udaipur",
    state: "Rajasthan",
    tagline: "Lake palaces, rooftop sunsets and Aravalli drives",
    bestMonths: ["Jul", "Aug"],
    avoidMonths: ["Dec", "Feb"],
    monthlyIndex: [76, 82, 66, 54, 46, 40, 32, 34, 44, 68, 86, 92],
    priceIndex: 61,
    verdict: "watch",
    cheapestMode: "bus",
    fromMumbai: 1120,
    emoji: "⛵",
  },
  {
    id: "munnar",
    name: "Munnar",
    state: "Kerala",
    tagline: "Tea estates, misty ridges and spice trails",
    bestMonths: ["Jun", "Jul"],
    avoidMonths: ["Dec", "Apr"],
    monthlyIndex: [70, 62, 66, 84, 60, 34, 30, 38, 48, 64, 74, 90],
    priceIndex: 34,
    verdict: "now",
    cheapestMode: "train",
    fromMumbai: 2260,
    emoji: "🍃",
  },
  {
    id: "varanasi",
    name: "Varanasi",
    state: "Uttar Pradesh",
    tagline: "Ghat mornings, silk lanes and endless chai",
    bestMonths: ["Aug", "Sep"],
    avoidMonths: ["Oct", "Nov"],
    monthlyIndex: [64, 58, 54, 50, 44, 42, 38, 32, 36, 88, 92, 70],
    priceIndex: 47,
    verdict: "now",
    cheapestMode: "train",
    fromMumbai: 1450,
    emoji: "🪔",
  },
  {
    id: "shillong",
    name: "Shillong",
    state: "Meghalaya",
    tagline: "Living root bridges, waterfalls and Khasi hills",
    bestMonths: ["Mar", "Apr"],
    avoidMonths: ["Jun", "Jul"],
    monthlyIndex: [58, 52, 44, 46, 62, 90, 94, 80, 66, 60, 54, 68],
    priceIndex: 66,
    verdict: "wait",
    cheapestMode: "flight",
    fromMumbai: 5680,
    emoji: "🌧️",
  },
];

export function priceHistory(days: number, basePrice: number) {
  const out: { day: string; price: number }[] = [];
  let value = basePrice * 1.08;
  for (let i = days - 1; i >= 0; i--) {
    const wobble = Math.sin(i * 0.7) * basePrice * 0.045 + Math.cos(i * 0.31) * basePrice * 0.03;
    value = basePrice + wobble - (i / days) * basePrice * 0.06;
    out.push({
      day: i === 0 ? "Today" : `-${i}d`,
      price: Math.round(value / 10) * 10,
    });
  }
  return out;
}

export const GROUP_MEMBERS: GroupMember[] = [
  { id: "m1", name: "Mahek", avatarInitials: "MJ" },
  { id: "m2", name: "Aarav", avatarInitials: "AR" },
  { id: "m3", name: "Neha", avatarInitials: "NS" },
  { id: "m4", name: "Rohit", avatarInitials: "RK" },
];

export const INITIAL_EXPENSES: Expense[] = [
  {
    id: "e1",
    title: "Rajdhani tickets (4 berths)",
    category: "Travel",
    amount: 11020,
    paidBy: "m1",
    splitMode: "equal",
    shares: {},
  },
  {
    id: "e2",
    title: "Homestay in Paharganj · 2 nights",
    category: "Stay",
    amount: 7200,
    paidBy: "m2",
    splitMode: "equal",
    shares: {},
  },
  {
    id: "e3",
    title: "Dinner at Karim's",
    category: "Food",
    amount: 2840,
    paidBy: "m3",
    splitMode: "custom",
    shares: { m1: 900, m2: 640, m3: 900, m4: 400 },
  },
  {
    id: "e4",
    title: "Qutub Minar + Red Fort passes",
    category: "Activities",
    amount: 1600,
    paidBy: "m4",
    splitMode: "equal",
    shares: {},
  },
];

export const TRAVEL_GROUPS: TravelGroup[] = [
  {
    id: "g1",
    name: "Himachal Her-Trails",
    route: "Delhi → Manali → Kasol",
    dates: "18–24 Sep",
    type: "women-only",
    verified: true,
    spots: 8,
    filled: 6,
    hostName: "Ritika S.",
    hostRating: 4.9,
    safetyScore: 94,
    tags: ["Women only", "KYC verified hosts", "Daytime transfers"],
  },
  {
    id: "g2",
    name: "Goa Monsoon Sisters",
    route: "Mumbai → Goa",
    dates: "12–15 Sep",
    type: "women-only",
    verified: true,
    spots: 10,
    filled: 4,
    hostName: "Farida K.",
    hostRating: 4.8,
    safetyScore: 91,
    tags: ["Women only", "Train travel", "Verified stays"],
  },
  {
    id: "g3",
    name: "Rajasthan Fort Circuit",
    route: "Jaipur → Jodhpur → Udaipur",
    dates: "27 Sep – 3 Oct",
    type: "co-ed",
    verified: true,
    spots: 14,
    filled: 11,
    hostName: "Team Wander",
    hostRating: 4.7,
    safetyScore: 86,
    tags: ["KYC verified", "Mixed group", "Group discount"],
  },
  {
    id: "g4",
    name: "Rishikesh Rafting Weekend",
    route: "Delhi → Rishikesh",
    dates: "20–22 Sep",
    type: "co-ed",
    verified: false,
    spots: 12,
    filled: 5,
    hostName: "Aman T.",
    hostRating: 4.4,
    safetyScore: 72,
    tags: ["Mixed group", "Adventure", "KYC pending"],
  },
];

export const STAY_SOLO_TIPS = [
  {
    title: "Arrive before dusk",
    body: "Filter for journeys landing between 07:00 and 18:00 — TravelWise flags night arrivals in your safety score.",
  },
  {
    title: "Share your live journey",
    body: "Send a tracking link to two contacts. Trains and SmartBuses on this route both support live tracking.",
  },
  {
    title: "Pick verified stays near transit",
    body: "Stays within 2 km of the station score higher on our late-arrival walkability check.",
  },
  {
    title: "Book women-only coaches early",
    body: "Ladies' coaches on the Rajdhani and women-only rows on SmartBus sell out roughly 9 days ahead.",
  },
];

export const REWARD_TIERS = [
  { name: "Explorer", points: 0, perks: ["Fare alerts", "Basic price trends"] },
  { name: "Voyager", points: 2500, perks: ["Flexible-date charts", "Group splitter"] },
  { name: "Navigator", points: 6000, perks: ["Priority safety scores", "Eco route boosts"] },
  { name: "Pro", points: 12000, perks: ["Free date changes", "Concierge support"] },
];
